version: "3"

services:
  #Database
  db:
    image: mysql:5.7
    volumes:
      - davidluclubdb_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - davidluclubwpsite

  #phpmyadmin
  #acc:wordpress,pwd:wordpress
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - davidluclubwpsite

  #Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "8007:80"
    restart: always
    # when install syncronize root directory & /var/www/html directory
    volumes: ["./wordpress:/var/www/html"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - davidluclubwpsite
networks:
  davidluclubwpsite:
volumes:
  davidluclubdb_data:
